### ISSUE TITLE
Grunt 0.5 "Update Release"

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#1045]
My proposal here is to make Grunt 0.5 an "Update Release". Meaning this release will mostly consist of updates and fixes that can't be landed with a minor bump. Efforts such as node-task will probably take longer than expected and in my opinion that should be pushed to 0.6. The plugin ecosystem should be able to update to this release with minimal effort.
## Include in 0.5 (draft list):
- [ ] https://github.com/gruntjs/grunt/issues/908 - Update nopt to 2.x.x
- [ ]  Bump other dependencies
- [ ]  https://github.com/gruntjs/grunt/pull/986 - Remove the words 'without errors.'
- [ ]  https://github.com/gruntjs/grunt/issues/911 - Add .coffee, .ls loading
- [ ]  Add https://github.com/cowboy/node-globule
- [ ]  https://github.com/gruntjs/grunt/issues/810 Add specific force
- [ ]  Remove external dependencies in grunt.util.... 
- [ ] https://github.com/gruntjs/grunt/pull/864 Always print stack traces 
- [ ] https://github.com/gruntjs/grunt/pull/732 - grunt.file.copy preserves permissions
- [ ] https://github.com/gruntjs/grunt/issues/979 - Expand mode clobbers
- [ ] https://github.com/gruntjs/grunt/pull/699 - Improve Spawn, add a callback
- [ ]  **Anything that is blocking** `grunt-contrib-*`
- [ ]  Warning on grunt.util.use
- [ ]  Warning on Node 0.8
- [ ]  ....
## 0.next:
- **Drop Node.JS 0.8 support**
- https://github.com/gruntjs/grunt/issues/943 Ship grunt-cli with core grunt
- https://github.com/gruntjs/grunt/issues/1048 - Organize Gruntfile by Feature
- https://github.com/gruntjs/grunt/issues/975 loadTasks as they are needed
- [node-task](https://github.com/node-task/spec/wiki)
- new logging with https://github.com/cowboy/node-prolog
- ...

Thoughts? @cowboy @tkellen @shama and everyone else...

**Comment by timomayer** [comment]
+1 for a word on the future of grunt. for me it seems grunt is dead :/

**Comment by monolithed** [comment]
+1. i'd like to hear anything about the working process as well.
