### ISSUE TITLE
final 0.4.0 checklist

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#663]
## everything
- [x] git tag eg "v0.4.0" (use the v please) and push tag to github!
## grunt
- [x] bump version to 0.4.0
- [x] update package.json to refer to final grunt plugin versions
- [x] ensure all URLs point to gruntjs.com
- [x] update readme
- [x] npm publish as latest
## grunt-cli
- [x] already done
## grunt-init
- [x] bump version to 0.2.0
- [x] update package.json to refer to final grunt, grunt plugin versions
- [x] ensure all URLs point to gruntjs.com
## grunt-init templates
- [x] update templates to reference final grunt, grunt plugin versions
- [x] ensure gruntplugin template actually makes sense
- [x] add peerDependencies to gruntplugin template
- [x] yeoman?
## grunt-contrib-internal
- [x] remove "pre-release" note @ top
- [x] ensure template references the configuring tasks guide
- [x] add `filemappings` flag that generates content referencing that part of the configuring tasks guide
## contrib plugins
- [x] bump version to non-rc final
- [x] update package.json to refer to final grunt, grunt plugins
- [x] update docs to point to task configuration docs
- [x] remove redundant docs
- [x] ensure all URLs point to gruntjs.com
- [x] ensure the "gruntplugin" keyword is specified in package.json
- [x] add peerDependencies to all grunt plugins
## all non-former-core contrib plugins
- [x] Document which major version number still works with 0.3-stable in docs/overview.
## grunt-contrib
- [x] update
- [x] don't deprecate, maintain forever
## ecosystem
- [x] post a message on every gruntplugin repo with a link and short explanation about how to upgrade their task.
- [x] blog about 0.4 release (bocoup guest post explaining how we broke grunt up, where we are headed etc).
## website
- [x] write home page copy
- [x] write plugins page copy
- [x] write inaugural news post
- [x] finish!
